version: 2

sources:
- name: dwh
tables:
- name: sakila_actor                      
- name:  sakila_actor_info                 
- name:  sakila_address                    
- name:  sakila_category                   
- name:  sakila_city                       
- name:  sakila_country                    
- name:  sakila_customer                   
- name:  sakila_customer_list              
- name:  sakila_film                       
- name:  sakila_film_actor                 
- name:  sakila_film_category              
- name:  sakila_film_list                  
- name:  sakila_film_text                  
- name:  sakila_inventory                  
- name:  sakila_language                   
- name:  sakila_nicer_but_slower_film_list 
- name:  sakila_payment                    
- name:  sakila_rental                     
- name:  sakila_sales_by_film_category     
- name:  sakila_sales_by_store             
- name:  sakila_staff                      
- name:  sakila_staff_list                 
- name:  sakila_store                      